

image: node:16.13.0

definitions:
  caches:
    nextcache: .next/cache
    
pipelines:
  branches:
    master:
      - step:
          name: Deploy to development
          deployment: Development
          size: 2x
          caches:
            - node
            - nextcache
          script:
            - apt-get update
            - apt-get install -y curl jq
            - apt-get install -y zip
            
            - npm install
            - npm run build:dev
           
            - declare -x VERSION=$(jq -r '.version' package.json)
            - echo $VERSION
            - zip -r application.zip .
            - pipe: atlassian/aws-code-deploy:0.2.5
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
                VERSION_LABEL: '${BITBUCKET_BUILD_NUMBER}-$APPLICATION_NAME-$VERSION'
            - pipe: atlassian/aws-code-deploy:0.2.5
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'deploy'
                WAIT: 'true'
                VERSION_LABEL: '${BITBUCKET_BUILD_NUMBER}-$APPLICATION_NAME-$VERSION'
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
    release/*:
      - step:
          name: Deploy to production
          deployment: Production
          size: 2x
          caches:
            - node
            - nextcache
          script:
            - apt-get update
            - apt-get install -y curl jq
            - apt-get install -y zip

            - npm install
            - npm run build:prod

            - declare -x VERSION=$(jq -r '.version' package.json)
            - echo $VERSION
            - zip -r application.zip .
            - pipe: atlassian/aws-code-deploy:0.2.5
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
                VERSION_LABEL: '${BITBUCKET_BUILD_NUMBER}-release-$APPLICATION_NAME-$VERSION'
            - pipe: atlassian/aws-code-deploy:0.2.5
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'deploy'
                WAIT: 'true'
                VERSION_LABEL: '${BITBUCKET_BUILD_NUMBER}-release-$APPLICATION_NAME-$VERSION'
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
                